# critcal
install git
install bash-completion
install macvim
install tmux
install reattach-to-user-namespace
install ctags

# less critical
install python
install wkhtmltopdf
install qt
install redis
install wget
install mysql
install imagemagick
install ack
install proctools
install fortune
install htop
install watch
install lynx
install gcal
install dos2unix
install jq
install mplayer
install rbenv
install tree
install markdown
install gpg
install tig
install hg
install ranger
install ngrok
install jrnl
install httpie
install pgcli
