install python
install wkhtmltopdf
install qt
install postgres
install redis
install wget
install git
install mysql
install imagemagick
install ack
install proctools
install fortune
install htop
install watch
install lynx
install gcal
install tmux
install macvim
install reattach-to-user-namespace
install bash-completion
install ctags
install dos2unix
install jq
install mplayer
install rbenv
install tree
install markdown
install gpg
install node
install tig
install hg
install ranger
install ngrok
install jrnl
