#!/bin/bash

cat <<- _EOF_
<!doctype html>
<html>
  <head>
    <title></title>
    <!-- <link href="" media="screen, projection" rel="stylesheet" type="text/css"> -->
  </head>
  <body>
    <div></div>
    <script></script>
  </body>
</html>
_EOF_
